In [1]:
import torch
import torch.nn as nn
def corr2d(X, k):
    n_w, n_h = X.shape
    k_w, k_h = k.shape
    ret_mat = torch.zeros((n_w - k_w + 1, n_h - k_h + 1))
    for i in range(n_w - k_w + 1):
        for j in range(n_h - k_h + 1):
            ret_mat[i, j] = (X[i:i+k_w, j:j+k_h] * k).sum()
    return ret_mat

X = torch.arange(9).reshape((3,3))
K = torch.arange(4).reshape((2,2))

corr2d(X, K)

tensor([[19., 25.],
        [37., 43.]])

In [17]:
X = torch.ones((6, 8))
X[:, 2:6] = 0
k = torch.tensor([[1, -1]])
Y = corr2d(X, k)
print(X, Y)

X = X.reshape((1,1) + X.shape)
Y = Y.reshape((1,1) + Y.shape)

tensor([[1., 1., 0., 0., 0., 0., 1., 1.],
        [1., 1., 0., 0., 0., 0., 1., 1.],
        [1., 1., 0., 0., 0., 0., 1., 1.],
        [1., 1., 0., 0., 0., 0., 1., 1.],
        [1., 1., 0., 0., 0., 0., 1., 1.],
        [1., 1., 0., 0., 0., 0., 1., 1.]]) tensor([[ 0.,  1.,  0.,  0.,  0., -1.,  0.],
        [ 0.,  1.,  0.,  0.,  0., -1.,  0.],
        [ 0.,  1.,  0.,  0.,  0., -1.,  0.],
        [ 0.,  1.,  0.,  0.,  0., -1.,  0.],
        [ 0.,  1.,  0.,  0.,  0., -1.,  0.],
        [ 0.,  1.,  0.,  0.,  0., -1.,  0.]])


In [30]:
net = nn.Conv2d(1, 1, kernel_size=(1,2), bias=False)
updater = torch.optim.SGD(net.parameters(), lr = 0.01)

for i in range(100):
    y_hat = net(X)
    l = ((Y - y_hat)**2).sum()
    l.backward()
    updater.step()
    updater.zero_grad()
    if l.item() < 1e-8:
        print("max_iter =", i)
        break
print(Y)
print(y_hat)
print(net.weight)

max_iter = 85
tensor([[[[ 0.,  1.,  0.,  0.,  0., -1.,  0.],
          [ 0.,  1.,  0.,  0.,  0., -1.,  0.],
          [ 0.,  1.,  0.,  0.,  0., -1.,  0.],
          [ 0.,  1.,  0.,  0.,  0., -1.,  0.],
          [ 0.,  1.,  0.,  0.,  0., -1.,  0.],
          [ 0.,  1.,  0.,  0.,  0., -1.,  0.]]]])
tensor([[[[ 0.0000,  1.0000,  0.0000,  0.0000,  0.0000, -1.0000,  0.0000],
          [ 0.0000,  1.0000,  0.0000,  0.0000,  0.0000, -1.0000,  0.0000],
          [ 0.0000,  1.0000,  0.0000,  0.0000,  0.0000, -1.0000,  0.0000],
          [ 0.0000,  1.0000,  0.0000,  0.0000,  0.0000, -1.0000,  0.0000],
          [ 0.0000,  1.0000,  0.0000,  0.0000,  0.0000, -1.0000,  0.0000],
          [ 0.0000,  1.0000,  0.0000,  0.0000,  0.0000, -1.0000,  0.0000]]]],
       grad_fn=<ConvolutionBackward0>)
Parameter containing:
tensor([[[[ 1.0000, -1.0000]]]], requires_grad=True)
