In [37]:
import torch
import torch.nn as nn

def process(x, pool_size, mode):
    h, w = x.shape[-2], X.shape[-1]
    p0, p1 = pool_size
    h_o, w_o = h - p0 + 1, w - p1 + 1
    y = torch.zeros((h_o, w_o))
    for i in range(h_o):
        for j in range(w_o):
            if mode == 'max':
                y[i, j] = x[i: i+p0, j: j+p1].max()
            elif mode == 'min':
                y[i, j] = x[i: i+p0, j: j+p1].min()
            else:
                y[i, j] = x[i: i+p0, j: j+p1].mean()
    return y

def pool_2d(X, pool_size, mode='max'):
    assert(mode == 'max' or mode == 'min' or mode == 'mean')
    assert(X.dim() == 4)
    n_batch, n_chan, n_h, n_w = X.shape
    p0, p1 = pool_size
    h_o, w_o = n_h - p0 + 1, n_w - p1 + 1
    X = X.reshape((-1, n_h, n_w))
    Y = torch.stack([process(x, pool_size, mode) for x in X], 0)
    return Y.reshape(n_batch, n_chan, h_o, w_o)

X = torch.arange(75, dtype=torch.float32).reshape(1, 3, 5, 5)
pool = nn.MaxPool2d(3, stride=1, padding=0)

print(pool(X) == pool_2d(X, (3,3), mode='max'))

#X = torch.arange(9).reshape(3, 3)
#print(X)
#x,y = X.max(dim=0)

                

tensor([[[[True, True, True],
          [True, True, True],
          [True, True, True]],

         [[True, True, True],
          [True, True, True],
          [True, True, True]],

         [[True, True, True],
          [True, True, True],
          [True, True, True]]]])


In [51]:
a=torch.randn(2,3,4)
b=torch.randn(2,3,4)
print(a)  # 2, 3, 4
print(b) # 2, 3, 4

f=torch.stack([a, b], dim=2)  # 2, 3, 2, 4
f

tensor([[[ 0.6757,  0.0218, -0.5498,  0.8284],
         [-0.5993, -1.4082,  1.7136, -0.1557],
         [ 0.9654,  0.2352,  1.2410, -0.2092]],

        [[ 0.9575, -0.3247,  0.6956, -0.3899],
         [-0.7129,  0.7919,  0.5173, -0.7772],
         [ 1.2880,  0.1870,  0.1663, -0.9995]]])
tensor([[[-1.6710, -0.5614, -0.7989, -0.0652],
         [ 0.9862, -0.9058,  1.4343, -0.0328],
         [ 0.3933,  0.7228, -0.4489,  0.0322]],

        [[ 0.0487,  0.7793,  1.3150,  0.2885],
         [ 1.2087,  0.9152, -0.0345, -1.4473],
         [-0.0117,  0.2162, -0.2963, -1.5880]]])


tensor([[[[ 0.6757,  0.0218, -0.5498,  0.8284],
          [-1.6710, -0.5614, -0.7989, -0.0652]],

         [[-0.5993, -1.4082,  1.7136, -0.1557],
          [ 0.9862, -0.9058,  1.4343, -0.0328]],

         [[ 0.9654,  0.2352,  1.2410, -0.2092],
          [ 0.3933,  0.7228, -0.4489,  0.0322]]],


        [[[ 0.9575, -0.3247,  0.6956, -0.3899],
          [ 0.0487,  0.7793,  1.3150,  0.2885]],

         [[-0.7129,  0.7919,  0.5173, -0.7772],
          [ 1.2087,  0.9152, -0.0345, -1.4473]],

         [[ 1.2880,  0.1870,  0.1663, -0.9995],
          [-0.0117,  0.2162, -0.2963, -1.5880]]]])